[build]
publish = "dist"
command = "npm run build"

[[redirects]]
  from = "/ingest/static/*"
  to = "https://eu-assets.i.posthog.com/static/:splat"
  host = "eu-assets.i.posthog.com"
  status = 200
  force = true

[[redirects]]
  from = "/ingest/*"
  to = "https://eu.i.posthog.com/:splat"
  host = "eu.i.posthog.com"
  status = 200
  force = true